arcoiris=("Azul","Verde","Rojo","Amarillo")
print (arcoiris)
print("--Longitud Arcoriris--")
print(len(arcoiris))
animales=("Pantera", 20, "Estatura", 1.7)
print(animales)
print("--Elementos de la tupla--")
print(animales[2])
rateros = ("juan", "ana", "pedro")
y = list(rateros)
y[1] = "polainas"
x = tuple(y)
print(x)
print("Agregando elementos")
Nanimal=("Bobby", "Chetos")
y = list (Nanimal)
y.append("Tontolin")
otratupla= tuple(y)
print(otratupla)
print("Uso de for en tuplas")
for elcolor in arcoiris:
    print(elcolor)